#In this example, the 'check-status' step is recursively repeated until
# the result is finished
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: api-call-recursive-
spec:
  entrypoint: trigger-job
  templates:
  - name: trigger-job
    steps:
    - - name: call-submitjob-api  # 1 submit job
        template: call-api
        arguments:
          parameters: [{name: url, value: "https://www.google.com"}]
    - - name: check-status # keep checking job status
        template: check-status
        arguments:
          parameters: [{name: url, value: "https://www.google.com"}]

  - name: check-status # recursive
    inputs:
    parameters:
      - name: url
    steps:
    - - name: wait 
        template: wait
     #  call-status returns true if processing is done  
    - - name: call-jobstatus-api
        template: call-status # call job status api
        arguments:
          parameters: [{name: url, value: "{{inputs.parameters.url}}"}]
      - name: processing
        template: check-status # go back if returns processing


  - name: call-api
    inputs:
      parameters:
        - name: url
    http:
      successCondition: "response.statusCode == 201" # Succeed only if status is 201, otherwise fail
      url: "{{inputs.parameters.url}}"
  - name: wait
    suspend:
      duration: "20"    # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
  - name: call-status
    inputs:
      parameters:
        - name: url
    http:
      successCondition: "response.body contains \"done\""
      url: "{{inputs.parameters.url}}"


     # http output https://github.com/argoproj/argo-workflows/discussions/7376
