apiVersion: apps/v1
kind: Deployment
metadata:
 name: php-apache
spec:
 selector:
   matchLabels:
     run: php-apache
 replicas: 100
 template:
   metadata:
     labels:
       run: php-apache
   spec:
     containers:
     - name: php-apache
       image: k8s.gcr.io/hpa-example
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 1000m
         requests:
           cpu: 1000m