apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-httptrigger
  namespace: argo-events
spec:
  dependencies:
    - name: test-dep
      eventSourceName: aws-sqs
      eventName: example
  triggers:
    - template:
        name: http-get-trigger
        http:
          url: https://sandbox.api.service.nhs.uk/hello-world/hello/world
          payload:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                contextKey: type
              dest: type
          method: GET
      retryStrategy:
        steps: 3
        duration: 3s