apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  - configmaps
  - events
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - deletecollection
  - annotate
  - patch
  - label
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - patch
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - annotate
  - patch
  - label
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - annotate
  - patch
  - label
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - annotate
  - patch
  - label
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - deletecollection
  - annotate
  - patch
  - label
