apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-20
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-20
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-20
    spec:
      containers:
      - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
        imagePullPolicy: Always
        name: app-20
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-20
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-20

